export default {
name:['/news/create','/pics/create','/articles/pics','/articles/movies','/articles/music','/interaction/tea','/interaction/topic'],
category:[{
        name:'/news/create',
        tag:true,
        url:false,
        description:false
      },{
        name:'/pics/create',
        tag:true,
        url:false,
        description:true
      },{
        name:'/articles/pics',
        tag:true,
        url:false,
        description:false       
      },{
        name:'/articles/movies',
        tag:true,
        url:true,
        description:true        
      },{
        name:'/articles/music',
        tag:true,
        url:true,
        description:true        
      },{
        name:'/interaction/tea',
        tag:true,
        url:false,
        description:false        
      },{
        name:'/interaction/topic',
        tag:true,
        url:false,
        description:false         
      }]
}