export default {
// name:['/news/create','/pics/create','/articles/pics','/articles/movies','/articles/music','/interaction/tea','/interaction/topic'],
category:[{
        name:'/news/create',
        tag:true,
        url:false,
        edit:true,
        textarea:false
      },{
        name:'/pics/create',
        tag:true,
        url:false,
        edit:false,
        textarea:true
      },{
        name:'/articles/pics',
        tag:true,
        url:false,
        edit:true,
        textarea:false       
      },{
        name:'/articles/movies',
        tag:true,
        url:true,
        edit:false,
        textarea:true        
      },{
        name:'/articles/music',
        tag:true,
        url:true,
        edit:false,
        textarea:true        
      },{
        name:'/interaction/tea',
        tag:true,
        url:false,
        edit:true,
        textarea:false        
      },{
        name:'/interaction/topic',
        tag:true,
        url:false,
        edit:true,
        textarea:false         
      }]
}